// <auto-generated />
using System;
using MarvelCharacters.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarvelCharacters.Data.Migrations
{
    [DbContext(typeof(MarvelCharactersContext))]
    [Migration("20200202192039_Comics")]
    partial class Comics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarvelCharacters.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Spider-Man is a fictional superhero created by writer-editor Stan Lee and writer-artist Steve Ditko. He first appeared in the anthology comic book Amazing Fantasy #15 (August 1962) in the Silver Age of Comic Books",
                            Modified = new DateTime(2020, 2, 2, 16, 20, 39, 520, DateTimeKind.Local).AddTicks(4192),
                            Name = "Spider-Man"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Iron Man is a fictional superhero appearing in American comic books published by Marvel Comics. The character was co-created by writer and editor Stan Lee, developed by scripter Larry Lieber, and designed by artists Don Heck and Jack Kirby. The character made his first appearance in Tales of Suspense #39 (cover dated March 1963), and received his own title in Iron Man #1 (May 1968)",
                            Modified = new DateTime(2020, 2, 2, 16, 20, 39, 521, DateTimeKind.Local).AddTicks(2834),
                            Name = "Iron Man"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Captain America is a fictional superhero appearing in American comic books published by Marvel Comics. Created by cartoonists Joe Simon and Jack Kirby, the character first appeared in Captain America Comics #1 (cover dated March 1941) from Timely Comics, a predecessor of Marvel Comics",
                            Modified = new DateTime(2020, 2, 2, 16, 20, 39, 521, DateTimeKind.Local).AddTicks(2855),
                            Name = "Captain America"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Thor Odinson is a fictional superhero appearing in American comic books published by Marvel Comics. The character, which is based on the Norse deity of the same name, is the Asgardian god of thunder who possesses the enchanted hammer, Mjolnir, which grants him the ability to fly and manipulate weather amongst his other superhuman attributes.",
                            Modified = new DateTime(2020, 2, 2, 16, 20, 39, 521, DateTimeKind.Local).AddTicks(2858),
                            Name = "Thor"
                        });
                });

            modelBuilder.Entity("MarvelCharacters.Models.Comic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Comics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Amazing Spider-Man is an American comic book series published by Marvel Comics, featuring the fictional superhero Spider-Man as its main protagonist. Being in the mainstream continuity of the franchise, it began publication in 1963 as a monthly periodical and was published continuously, with a brief interruption in 1995, until its relaunch with a new numbering order in 1999. In 2003 the series reverted to the numbering order of the first volume.",
                            Modified = new DateTime(2020, 2, 2, 16, 20, 39, 522, DateTimeKind.Local).AddTicks(5120),
                            Title = "The Amazing Spider-Man"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Avengers are a fictional team of superheroes appearing in American comic books published by Marvel Comics. The team made its debut in The Avengers #1 (cover-dated Sept. 1963), created by writer-editor Stan Lee and artist/co-plotter Jack Kirby. The Avengers is Lee and Kirby's renovation of a previous superhero team, All-Winners Squad, who appeared in comic books series published by Marvel Comics' predecessor Timely Comics.",
                            Modified = new DateTime(2020, 2, 2, 16, 20, 39, 522, DateTimeKind.Local).AddTicks(5631),
                            Title = "The Avengers"
                        });
                });

            modelBuilder.Entity("MarvelCharacters.Models.Relationships.CharacterComic", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ComicId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "ComicId");

                    b.HasIndex("ComicId");

                    b.ToTable("CharacterComics");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            ComicId = 1
                        },
                        new
                        {
                            CharacterId = 1,
                            ComicId = 2
                        },
                        new
                        {
                            CharacterId = 2,
                            ComicId = 2
                        },
                        new
                        {
                            CharacterId = 3,
                            ComicId = 2
                        },
                        new
                        {
                            CharacterId = 4,
                            ComicId = 2
                        });
                });

            modelBuilder.Entity("MarvelCharacters.Models.Relationships.CharacterComic", b =>
                {
                    b.HasOne("MarvelCharacters.Models.Character", "Character")
                        .WithMany("CharacterComics")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarvelCharacters.Models.Comic", "Comic")
                        .WithMany("CharacterComics")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
